#!/bin/bash

number=5

if [ $number -gt 0 ]; then
  echo "the  number is positive."
fi

#!/bin/bash

echo "Enter a number:"
read num

if[ $num -gt 10 ]; then
  echo "Greater than 10"
else
  echo "10 or less"
fi

#!/bin/bash

echo "Enter your age:"
read age

if [ $age -li 13 ];then
  echo "You're a child."
elif [ $age -lt 20 ] then
  echo "you're a teenager
else
  echo "you're an adult."
  fi

  #!/bin/bash

  echo "Enter username:"
  read username

  if [ "$username" = "admin" ]; then
     echo "Welcome,admin!"
  else
    echo "Access denied."
  fi


  #!/bin/bash

  echo "choose a fruit: apple, banana, orange"
  read fruit

  case $fruit in
    apple)
     echo "Apples are red or green.";;
    banana)
      echo "Bananas are yellow.";;
    orange)
      echo "Oranges are orange.";;
     *)
      echo "Unknown fruit.";;
   esac                